#!/usr/bin/python
# -*- coding:utf-8 -*-

CODE_OK                         = 0
CODE_LOGIN_REQUIRED             = -100
CODE_USER_OR_PASS_IS_WRONG      = -101
CODE_LACK_OF_POINTS             = -102
CODE_ACCOUNT_IS_BEING_RENTED    = -103
CODE_ONE_ACCOUNT_ONE_SITE       = -104
CODE_NEED_VERIFICATION_CODE     = -105
CODE_INVALID_ACCOUNT            = -106
CODE_ACCOUNT_NOT_BEING_RENTED   = -107
CODE_NOT_ACCOUNT_OWNER          = -108
CODE_REACH_MAX_CONCURRENCY_USER = -109
